# Here we will create a pod for backend service and expose it using a service of type LoadBalancer from backend/Dockerfile

apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    labels:
        app: backend-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: backend-deployment
    template:
        metadata:
            labels:
                app: backend-deployment
        spec:
            containers:
            - name: backend
              image: backend:latest
              ports:
              - containerPort: 8000

              env:
              - name: MONGO_URI
                value: "mongodb://mongo-service:27017"
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
---

# Expose the backend service using a service of type LoadBalancer

apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    selector:
        app: backend-deployment
    ports:
    - protocol: TCP
      port: 8000 # Expose the service on port 8000 (That is external port)
      targetPort: 8000 # Forward the request to port 8000 of the pod (That is internal port)
    type: LoadBalancer


# Now we have both the backend and its service done we will now add the database service for the backend to connect to